//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mphweb.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class infltab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal infltab() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mphweb.Resources.infltab", typeof(infltab).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;86%&quot; class=&quot;table_style&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;14%&quot;  height=&quot;30&quot; rowspan=&quot;2&quot; class=&quot;td_style&quot;&gt;
        ///        падеж&lt;/td&gt;
        ///    &lt;td width=&quot;65%&quot;  height=&quot;22&quot; colspan=&quot;3&quot; class=&quot;td_style&quot;&gt;
        ///       единственное число &lt;/td&gt;
        ///    &lt;td width=&quot;31%&quot;  height=&quot;30&quot; rowspan=&quot;2&quot; class=&quot;td_s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_c1 {
            get {
                return ResourceManager.GetString("ru_c1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot;&gt;[WORD]&lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;&lt;/font&gt;&lt;/h4&gt; 
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;63%&quot; class=&quot;table_style&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;13%&quot; class=&quot;td_style&quot;&gt;
        ///     падеж&lt;/td&gt;
        ///    &lt;td width=&quot;22%&quot; class=&quot;td_style&quot;&gt;
        ///      муж. р.
        ///	&lt;/td&gt;
        ///    &lt;td width=&quot;24%&quot; class=&quot;td_style&quot;&gt;
        ///	жен. р.
        ///	&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;13%&quot; class=&quot;td_left [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_c2 {
            get {
                return ResourceManager.GetString("ru_c2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt; 
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///
        ///
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;41%&quot; class=&quot;table_style&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;22%&quot; class=&quot;td_style&quot;&gt;
        ///      падеж&lt;/td&gt;
        ///    &lt;td width=&quot;48%&quot; class=&quot;td_style&quot;&gt;&amp;nbsp;
        ///      
        ///    &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;22%&quot; class=&quot;td_left_style&quot;&gt;
        ///    именительный&lt;/td&gt;
        ///    &lt;td width=&quot;48%&quot; class [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_ck {
            get {
                return ResourceManager.GetString("ru_ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot;&gt;[WORD]&lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;&lt;/font&gt;&lt;/h4&gt; 
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;63%&quot; class=&quot;table_style&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;13%&quot; class=&quot;td_style&quot;&gt;
        ///     падеж&lt;/td&gt;
        ///    &lt;td width=&quot;22%&quot; class=&quot;td_style&quot;&gt;
        ///      единственное число &lt;/td&gt;
        ///    &lt;td width=&quot;24%&quot; class=&quot;td_style&quot;&gt;
        ///	множественное число &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_cp {
            get {
                return ResourceManager.GetString("ru_cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;83%&quot; &gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;15%&quot; rowspan=&quot;2&quot; &gt;
        ///      падеж&lt;/td&gt;
        ///    &lt;td width=&quot;63%&quot; colspan=&quot;3&quot; &gt;
        ///     единственное число &lt;/td&gt;
        ///    &lt;td width=&quot;32%&quot;  rowspan=&quot;2&quot; &gt;
        ///     множественное число &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;20%&quot; class=&quot;td_s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_d {
            get {
                return ResourceManager.GetString("ru_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;h4 align=&quot;center&quot;&gt;&lt;font color=&quot;#cc3300&quot;&gt;[WORD]&lt;span style=&quot;FONT-WEIGHT: 400&quot;&gt;
        ///&lt;/span&gt;&lt;/font&gt;&lt;span style=&quot;font-weight: 400&quot;&gt;
        ///&lt;font color=&quot;#008080&quot; &gt;–&lt;/font&gt;&lt;font color=&quot;#008080&quot;&gt; 
        /// [gram]&lt;/font&gt;&lt;/span&gt;&lt;/h4&gt; 
        ///
        ///&lt;h4 align=&quot;center&quot;&gt;&lt;i&gt;&lt;span style=&quot;font-weight: 400; font-style: italic&quot;&gt;[(sem comment)]&lt;/span&gt;&lt;/i&gt;&lt;/h4&gt;
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;64%&quot; height=&quot;253&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;19%&quot; bgcolor=&quot;#C0C0C0&quot; height=&quot;43&quot; align=&quot;center&quot;&gt;
        ///      &lt;p align=&quot;center&quot;&gt;&lt;span style=&quot;letter-spa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_f {
            get {
                return ResourceManager.GetString("ru_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;h4 align=&quot;center&quot;&gt;&lt;font color=&quot;#cc3300&quot;&gt;[WORD]&lt;span style=&quot;FONT-WEIGHT: 400&quot;&gt;
        ///&lt;/span&gt;&lt;/font&gt;&lt;span style=&quot;font-weight: 400&quot;&gt;
        ///&lt;font color=&quot;#008080&quot; &gt;–&lt;/font&gt;&lt;font color=&quot;#008080&quot;&gt; 
        /// [gram]&lt;/font&gt;&lt;/span&gt;&lt;/h4&gt; 
        ///
        ///&lt;h4 align=&quot;center&quot;&gt;&lt;i&gt;&lt;span style=&quot;font-weight: 400; font-style: italic&quot;&gt;[(sem comment)]&lt;/span&gt;&lt;/i&gt;&lt;/h4&gt;
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;63%&quot; height=&quot;245&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;13%&quot; bgcolor=&quot;#C0C0C0&quot; height=&quot;44&quot; align=&quot;center&quot;&gt;
        ///      &lt;p align=&quot;center&quot;&gt;&lt;span style=&quot;letter-spa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_f1 {
            get {
                return ResourceManager.GetString("ru_f1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///
        ///&lt;h4 align=&quot;center&quot;&gt;&lt;font color=&quot;#cc3300&quot;&gt;[WORD]&lt;span style=&quot;FONT-WEIGHT: 400&quot;&gt;
        ///&lt;/span&gt;&lt;/font&gt;&lt;span style=&quot;font-weight: 400&quot;&gt;
        ///&lt;font color=&quot;#008080&quot; &gt;–&lt;/font&gt;&lt;font color=&quot;#008080&quot;&gt; 
        /// [gram]&lt;/font&gt;&lt;/span&gt;&lt;/h4&gt; 
        ///
        ///&lt;h4 align=&quot;center&quot;&gt;&lt;i&gt;&lt;span style=&quot;font-weight: 400; font-style: italic&quot;&gt;[(sem comment)]&lt;/span&gt;&lt;/i&gt;&lt;/h4&gt;
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;58%&quot; height=&quot;245&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;13%&quot; bgcolor=&quot;#C0C0C0&quot; height=&quot;41&quot; align=&quot;center&quot;&gt;
        ///      &lt;p align=&quot;center&quot;&gt;&lt;span style=&quot;letter-s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_f2 {
            get {
                return ResourceManager.GetString("ru_f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  &lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot;&gt;[WORD]&lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;&lt;/font&gt;&lt;/h4&gt; 
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;63%&quot; class=&quot;table_style&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;13%&quot; class=&quot;td_style&quot;&gt;
        ///     падеж&lt;/td&gt;
        ///    &lt;td width=&quot;22%&quot; class=&quot;td_style&quot;&gt;
        ///      единственное число &lt;/td&gt;
        ///    &lt;td width=&quot;24%&quot; class=&quot;td_style&quot;&gt;
        ///	множественное число &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;13 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_i {
            get {
                return ResourceManager.GetString("ru_i", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;83%&quot; &gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;15%&quot; rowspan=&quot;2&quot; &gt;
        ///      падеж&lt;/td&gt;
        ///    &lt;td width=&quot;63%&quot; colspan=&quot;3&quot; &gt;
        ///     единственное число &lt;/td&gt;
        ///    &lt;td width=&quot;32%&quot;  rowspan=&quot;2&quot; &gt;
        ///     множественное число &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;20%&quot; class=&quot;td_s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_p {
            get {
                return ResourceManager.GetString("ru_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;71%&quot; cellspacing=&quot;1&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;101%&quot; class=&quot;td_left_style&quot;&gt;
        ///    Инфинитив&lt;/td&gt;
        ///    &lt;td width=&quot;85%&quot; colspan=&quot;2&quot; class=&quot;td_inner_center_style&quot;&gt;
        ///    Field__1_&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;101%&quot;&gt;&amp;nbsp;
        ///    &lt;/td&gt;
        ///    &lt;td width=&quot;85% [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_vd {
            get {
                return ResourceManager.GetString("ru_vd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;71%&quot; cellspacing=&quot;1&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td  class=&quot;td_left_style&quot;&gt;
        ///    Инфинитив&lt;/td&gt;
        ///    &lt;td width=&quot;85%&quot; colspan=&quot;2&quot; class=&quot;td_inner_center_style&quot;&gt;
        ///    Field__1_&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td &gt;&amp;nbsp;
        ///    &lt;/td&gt;
        ///    &lt;td width=&quot;85%&quot; class=&quot;td_style&quot;&gt;единс [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_vn {
            get {
                return ResourceManager.GetString("ru_vn", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;h4 align=&quot;center&quot;&gt;&lt;font color=&quot;#CC3300&quot;&gt; [WORD]&lt;/font&gt;&lt;font color=&quot;#008080&quot;&gt; &lt;/font&gt;
        ///&lt;span style=&quot;font-weight: 400&quot;&gt;&lt;font color=&quot;#008080&quot; &gt;–&lt;/font&gt;&lt;font color=&quot;#008080&quot;&gt; 
        /// [gram]&lt;/font&gt;&lt;/span&gt;&lt;/h4&gt;    
        ///&lt;h4 align=&quot;center&quot;&gt;&lt;i&gt;&lt;span style=&quot;font-weight: 400; font-style: italic&quot;&gt;[(sem comment)]&lt;/span&gt;&lt;/i&gt;&lt;/h4&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;71%&quot; cellspacing=&quot;1&quot; height=&quot;561&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;15%&quot; bgcolor=&quot;#C0C0C0&quot; height=&quot;29&quot;&gt;
        ///      &lt;p align=&quot;left&quot;&gt;&lt;span style=&quot;letter-spacing: 2&quot;&gt;&lt;b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_vnd {
            get {
                return ResourceManager.GetString("ru_vnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt; 
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///
        ///
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;41%&quot; class=&quot;table_style&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;22%&quot; class=&quot;td_style&quot;&gt;
        ///      падеж&lt;/td&gt;
        ///    &lt;td width=&quot;48%&quot; class=&quot;td_style&quot;&gt;&amp;nbsp;
        ///      
        ///    &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;22%&quot; class=&quot;td_left_style&quot;&gt;
        ///    именительный&lt;/td&gt;
        ///    &lt;td width=&quot;48%&quot; class [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_z {
            get {
                return ResourceManager.GetString("ru_z", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;83%&quot; &gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;15%&quot; rowspan=&quot;2&quot; &gt;
        ///      падеж&lt;/td&gt;
        ///    &lt;td width=&quot;63%&quot; colspan=&quot;3&quot; &gt;
        ///     единственное число &lt;/td&gt;
        ///    &lt;td width=&quot;32%&quot;  rowspan=&quot;2&quot; &gt;
        ///     множественное число &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;20%&quot; class=&quot;td_s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru_zp {
            get {
                return ResourceManager.GetString("ru_zp", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;86%&quot; class=&quot;table_style&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;14%&quot;  height=&quot;30&quot; rowspan=&quot;2&quot; class=&quot;td_style&quot;&gt;
        ///        відмінок&lt;/td&gt;
        ///    &lt;td width=&quot;65%&quot;  height=&quot;22&quot; colspan=&quot;3&quot; class=&quot;td_style&quot;&gt;
        ///       однина&lt;/td&gt;
        ///    &lt;td width=&quot;31%&quot;  height=&quot;30&quot; rowspan=&quot;2&quot; class=&quot;td_style&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_c1 {
            get {
                return ResourceManager.GetString("ua_c1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot;&gt;[WORD]&lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;&lt;/font&gt;&lt;/h4&gt; 
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;63%&quot; class=&quot;table_style&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;13%&quot; class=&quot;td_style&quot;&gt;
        ///     відмінок
        ///	&lt;/td&gt;
        ///    &lt;td width=&quot;22%&quot; class=&quot;td_style&quot;&gt;
        ///      чол. р.
        ///	&lt;/td&gt;
        ///    &lt;td width=&quot;24%&quot; class=&quot;td_style&quot;&gt;
        ///	жін. р.
        ///	&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;13%&quot; class=&quot;t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_c2 {
            get {
                return ResourceManager.GetString("ua_c2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///
        ///
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;41%&quot; class=&quot;table_style&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;22%&quot; class=&quot;td_style&quot;&gt;
        ///      відмінок&lt;/td&gt;
        ///    &lt;td width=&quot;48%&quot; class=&quot;td_style&quot;&gt;&amp;nbsp;
        ///      
        ///    &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;22%&quot; class=&quot;td_left_style&quot;&gt;
        ///    називний&lt;/td&gt;
        ///    &lt;td width=&quot;48%&quot; class=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_ck {
            get {
                return ResourceManager.GetString("ua_ck", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;77%&quot;  class=&quot;table_style&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;16%&quot; rowspan=&quot;2&quot; class=&quot;td_style&quot;&gt;
        ///      відмінок&lt;/td&gt;
        ///    &lt;td width=&quot;63%&quot;  colspan=&quot;3&quot; class=&quot;td_style&quot;&gt;
        ///     однина&lt;/td&gt;
        ///    &lt;td width=&quot;31%&quot; rowspan=&quot;2&quot; class=&quot;td_style&quot; &gt;
        ///      множина&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_cp {
            get {
                return ResourceManager.GetString("ua_cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///
        ///&lt;hr&gt;
        ///
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;83%&quot; &gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;15%&quot; rowspan=&quot;2&quot; &gt;
        ///      відмінок&lt;/td&gt;
        ///    &lt;td width=&quot;63%&quot; colspan=&quot;3&quot; &gt;
        ///     однина&lt;/td&gt;
        ///    &lt;td width=&quot;32%&quot;  rowspan=&quot;2&quot; &gt;
        ///     множина&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;20%&quot; class=&quot;td_style&quot;&gt;чол. р.&lt;/td&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_d {
            get {
                return ResourceManager.GetString("ua_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;64%&quot;&gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;19%&quot; &gt;
        ///     відмінок&lt;/td&gt;
        ///    &lt;td width=&quot;24%&quot; &gt;
        ///      чол. р.&lt;/td&gt;
        ///    &lt;td width=&quot;24%&quot;&gt;
        ///      жін. р. &lt;/td&gt;
        ///    &lt;td width=&quot;23%&quot; &gt;
        ///      множина&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;17%&quot; class=&quot;td_left_style&quot; &gt; 
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_f {
            get {
                return ResourceManager.GetString("ua_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;63%&quot;&gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;13%&quot; &gt;відмінок&lt;/td&gt;
        ///    &lt;td width=&quot;27%&quot;&gt;чол. і жін. р.&lt;/td&gt;
        ///    &lt;td width=&quot;26%&quot;&gt;множина&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;17%&quot; class=&quot;td_left_style&quot;&gt;називний&lt;/td&gt; 
        ///    &lt;td width=&quot;26%&quot; class=&quot;td_inner_style&quot;&gt;Field__1_&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_f1 {
            get {
                return ResourceManager.GetString("ua_f1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;58%&quot; &gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;13%&quot; &gt;
        ///     відмінок&lt;/td&gt;
        ///    &lt;td width=&quot;26%&quot; &gt;
        ///     чол. р.&lt;/td&gt;
        ///    &lt;td width=&quot;27%&quot; &gt;
        ///     множина&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;17%&quot; class=&quot;td_left_style&quot; &gt; 
        ///      називний&lt;/td&gt; 
        ///    &lt;td width=&quot;25%&quot; class [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_f2 {
            get {
                return ResourceManager.GetString("ua_f2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;51%&quot;&gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;23%&quot; &gt;
        ///      відмінок&lt;/td&gt;
        ///    &lt;td width=&quot;40%&quot;&gt;
        ///     однина&lt;/td&gt;
        ///    &lt;td width=&quot;37%&quot; &gt;
        ///     множина&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;14%&quot; class=&quot;td_left_style&quot; &gt; 
        ///      називний&lt;/td&gt; 
        ///    &lt;td width=&quot;40%&quot; class=&quot;td [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_i {
            get {
                return ResourceManager.GetString("ua_i", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;77%&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;16%&quot; rowspan=&quot;2&quot; class=&quot;td_style&quot; &gt;
        ///     відмінок&lt;/td&gt;
        ///    &lt;td width=&quot;63%&quot; colspan=&quot;3&quot; class=&quot;td_style&quot;&gt;
        ///    однина&lt;/td&gt;
        ///    &lt;td width=&quot;31%&quot; rowspan=&quot;2&quot; class=&quot;td_style&quot;&gt;
        ///     множина&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;19%&quot; class=&quot;td_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_p {
            get {
                return ResourceManager.GetString("ua_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;71%&quot; cellspacing=&quot;1&quot; &gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;15%&quot; class=&quot;td_style&quot;&gt;
        ///     Інфінітив&lt;/td&gt;
        ///    &lt;td width=&quot;85%&quot; colspan=&quot;2&quot; class=&quot;td_inner_center_style&quot;&gt;
        ///     Field__1_&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;15%&quot;&gt;&amp;nbsp;
        ///    &lt;/td&gt;
        ///    &lt;td width=&quot;40%&quot; &gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_vd {
            get {
                return ResourceManager.GetString("ua_vd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;71%&quot; cellspacing=&quot;1&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;15%&quot; class=&quot;td_left_style&quot;&gt;
        ///     Інфінітив&lt;/td&gt;
        ///    &lt;td width=&quot;85%&quot; colspan=&quot;2&quot; class=&quot;td_inner_center_style&quot;&gt;
        ///     Field__1_&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;15%&quot; class=&quot;td_left_style&quot;&gt;&amp;nbsp;
        ///    &lt;/td&gt;
        ///    &lt;td width [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_vn {
            get {
                return ResourceManager.GetString("ua_vn", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;71%&quot; cellspacing=&quot;1&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;15%&quot; class=&quot;td_left_style&quot;&gt;
        ///    Інфінітив&lt;/td&gt;
        ///    &lt;td width=&quot;85%&quot; colspan=&quot;2&quot; class=&quot;td_inner_center_style&quot;&gt;
        ///    Field__1_&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;15%&quot;&gt;&amp;nbsp;
        ///    &lt;/td&gt;
        ///    &lt;td width=&quot;40%&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_vnd {
            get {
                return ResourceManager.GetString("ua_vnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table align=&quot;center&quot; border=&quot;1&quot; width=&quot;43%&quot;&gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;34%&quot;&gt;відмінок&lt;/td&gt;
        ///    &lt;td width=&quot;68%&quot;&gt;&amp;nbsp;
        ///    &lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;25%&quot; class=&quot;td_left_style&quot;&gt;називний&lt;/td&gt; 
        ///    &lt;td width=&quot;68%&quot; class=&quot;td_inner_style&quot;&gt;Field__1_&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_z {
            get {
                return ResourceManager.GetString("ua_z", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  
        ///&lt;div align=&quot;center&quot;&gt; 
        ///	&lt;span class=&quot;word_style&quot; &gt;[WORD] &lt;/span&gt;
        ///	&lt;span class=&quot;gram_style&quot;&gt;– [gram]&lt;/span&gt;
        ///&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div align=&quot;center&quot; class=&quot;comment_style&quot;&gt;
        ///[(sem comment)]
        ///&lt;/div&gt;
        ///&lt;hr&gt;
        ///&lt;table border=&quot;1&quot; width=&quot;43%&quot; align=&quot;center&quot; &gt;
        ///  &lt;tr class=&quot;td_style&quot;&gt;
        ///    &lt;td width=&quot;16%&quot; rowspan=&quot;2&quot;&gt;відмінок&lt;/td&gt;
        ///    &lt;td width=&quot;63%&quot; colspan=&quot;3&quot;&gt;однина&lt;/td&gt;
        ///    &lt;td width=&quot;31%&quot; rowspan=&quot;2&quot;&gt;множина&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;td width=&quot;19%&quot; class=&quot;td_style&quot;&gt;чол. р.&lt;/td&gt;
        ///    &lt;td width=&quot;25%&quot; class=&quot;td_sty [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ua_zp {
            get {
                return ResourceManager.GetString("ua_zp", resourceCulture);
            }
        }
    }
}
