//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mphweb.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class idispl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal idispl() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mphweb.Resources.idispl", typeof(idispl).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Іншомовні цифрові лексикографічні системи.
        /// </summary>
        public static string bname_ru {
            get {
                return ResourceManager.GetString("bname_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Цифрове лексикографічне надбання України.
        /// </summary>
        public static string bname_ua {
            get {
                return ResourceManager.GetString("bname_ua", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Словники російської мови.
        /// </summary>
        public static string dict_ru_name {
            get {
                return ResourceManager.GetString("dict_ru_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Словники української мови.
        /// </summary>
        public static string dict_ua_name {
            get {
                return ResourceManager.GetString("dict_ua_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Граматичний словник.
        /// </summary>
        public static string tab_gram_name {
            get {
                return ResourceManager.GetString("tab_gram_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Словозмінні класи.
        /// </summary>
        public static string tab_inflectional_classes_name {
            get {
                return ResourceManager.GetString("tab_inflectional_classes_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Словник синонімів.
        /// </summary>
        public static string tab_synsets_name {
            get {
                return ResourceManager.GetString("tab_synsets_name", resourceCulture);
            }
        }
    }
}
